log:
  exp_name: napoleon_shadowy
guide:
  text: "A photo of Napoleon Bonaparte, shadowy"
  shape_path: shapes/napoleon.obj
  guidance_scale: 10
  use_zero123plus: True
optim:
  # seed: 10
  learn_max_z_normals: True
  alpha: -10
