log:
  exp_name: napoleon_0123plus_use_learned_max_z_normals-100
guide:
  text: "A photo of Napoleon Bonaparte, real person"
  append_direction: False
  shape_path: shapes/napoleon.obj
  use_zero123plus: True
optim:
  seed: 1000
  learn_max_z_normals: True
  alpha:               -10
