log:
  exp_name: napoleon_0123plus_use_learned_max_z_normals
guide:
  text: "A photo of Napoleon Bonaparte, real person"
  append_direction: False
  shape_path: shapes/napoleon.obj
  use_zero123plus: True
optim:
  seed: 0
  learn_max_z_normals: True
  alpha:               -1
  front_view_weight:   1.0
  project_back_front: False
