log:
  exp_name: spiderman_alpha-100
guide:
  text: "A photo of Spiderman"
  append_direction: False
  shape_path: shapes/human.obj
  guidance_scale: 10
  use_zero123plus: True
optim:
  learn_max_z_normals: True
  alpha: -100